"""2 migration

Revision ID: 0d8e1f28fd42
Revises: 4ff97fe5f243
Create Date: 2025-01-02 16:54:24.703418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d8e1f28fd42"
down_revision: Union[str, None] = "4ff97fe5f243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
