"""msg

Revision ID: 494ce4eb5d52
Revises: 75b34229e078
Create Date: 2025-01-02 18:00:05.402027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "494ce4eb5d52"
down_revision: Union[str, None] = "75b34229e078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("answer", "submission_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("lecture", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "phone_number", existing_type=sa.VARCHAR(length=17), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone_number", existing_type=sa.VARCHAR(length=17), nullable=False)
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("lecture", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("answer", "submission_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
