"""2 migration

Revision ID: b5dc9eb2d527
Revises: 0d8e1f28fd42
Create Date: 2025-01-02 16:55:03.543885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5dc9eb2d527"
down_revision: Union[str, None] = "0d8e1f28fd42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
