"""msg

Revision ID: 75b34229e078
Revises: 42919678ff38
Create Date: 2025-01-02 17:57:00.017918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75b34229e078"
down_revision: Union[str, None] = "42919678ff38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "photo", existing_type=postgresql.OID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "photo", existing_type=postgresql.OID(), nullable=False)
    # ### end Alembic commands ###
