services:
  flask-app:
    build: .
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: "/bin/bash -c 'python3 app.py'"


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: